# Site
name: "Caqqi"
title: "Caqqi"
description: "Java | Spring | Quarkus | Linux | Backend"
logo: 'assets/images/logo-caqqi.png'
favicon: 'assets/images/logo-caqqi.png'
baseurl: https://caqqi.com
google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# TODO: COLOCAR O discus
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bruno:
    name: Bruno Luz
    display_name: Bruno Luz
    photo: 'assets/images/bruno-luz.png'
    email: bsilva.se@gmail.com
    web: https://caqqi.com
    twitter: https://twitter.com/caqqi
    description: "Java | Spring | Linux | Code | Programmer."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Config Comments Disqus
site:
  disqus: caqqi  
comments: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
